# Generated by Django 4.0.2 on 2022-10-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.DateField()),
                ('intensity', models.IntegerField()),
                ('sector', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('insight', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('start_year', models.DateField()),
                ('added', models.DateField()),
                ('published', models.DateField()),
                ('impact', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('relevance', models.IntegerField()),
                ('pestle', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('likelihood', models.IntegerField()),
            ],
        ),
    ]
