# Generated by Django 4.0.2 on 2022-10-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_data_added_alter_data_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='intensity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='likelihood',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='relevance',
            field=models.CharField(max_length=50),
        ),
    ]
